<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Rusty" failures="1" tests="5" name="Personal Loan" time="0.161" errors="0" timestamp="2024-11-21T08:16:54 EST">
  <testcase classname="test.Day1" name="Demo" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.Demo(Day1.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Day2" name="ploan" time="0.009"/>
  <testcase classname="test.Day4" name="LoginAPIHomeLoan" time="0.005"/>
  <testcase classname="test.Day4" name="MobileLoginHomeLoan" time="0.004"/>
  <testcase classname="test.Day4" name="WebLoginHomeLoan" time="0.001"/>
  <testcase classname="test.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
